name: CI Pipeline

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run Tests
        run: |
          pytest --cov=myapp --cov-report=xml

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Application
        run: echo "Building application..."

      - name: Update README with Badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "![Build Status](https://github.com/your-username/github-actions-demo/actions/workflows/main.yml/badge.svg)" >> README.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update README with build status badge" || echo "No changes to commit"
          git push
